use std::sync::mpsc;
use tao::{
    event::Event,
    event_loop::{ControlFlow, EventLoop},
};
use thiserror::Error;
use tracing::info;
use tray_icon::{
    Icon, TrayIconBuilder,
    menu::{Menu, MenuEvent, MenuItem},
};

use crate::{
    AppCommand,
    config::APP_NAME,
    rpc::{RpcCommand, RpcState},
    ui::UiCommand,
};

#[derive(Debug, Error)]
pub enum TrayError {
    #[error("failed to create tray icon: {0}")]
    Icon(#[from] tray_icon::Error),

    #[error("failed to append menu item")]
    MenuAppend,

    #[error("icon decode failed")]
    IconDecode,
}

/// Runs the tray event loop.
///
/// The event loop must run on the main thread.
pub fn run_tray(
    tx: mpsc::Sender<AppCommand>,
    rpc_rx: mpsc::Receiver<RpcState>,
) -> Result<(), TrayError> {
    let event_loop = EventLoop::new();

    let menu = Menu::new();

    let state = MenuItem::new(APP_NAME, false, None);
    let show = MenuItem::new("Show Window", true, None);
    let start = MenuItem::new("Restart RPC", true, None);
    let stop = MenuItem::new("Stop RPC", true, None);
    let quit = MenuItem::new("Quit", true, None);

    menu.append(&state).map_err(|_| TrayError::MenuAppend)?;
    menu.append(&show).map_err(|_| TrayError::MenuAppend)?;
    menu.append(&start).map_err(|_| TrayError::MenuAppend)?;
    menu.append(&stop).map_err(|_| TrayError::MenuAppend)?;
    menu.append(&quit).map_err(|_| TrayError::MenuAppend)?;

    let icon = create_icon()?;

    let _tray = TrayIconBuilder::new()
        .with_tooltip(APP_NAME)
        .with_icon(icon)
        .with_menu(Box::new(menu))
        .build()?;

    let menu_rx = MenuEvent::receiver();

    info!("starting the tray event loop");

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::MainEventsCleared => {
                while let Ok(rpc_state) = rpc_rx.try_recv() {
                    match rpc_state {
                        RpcState::Connected => state.set_text("RPC: Connected"),
                        RpcState::Disconnected => state.set_text("RPC: Disconnected"),
                    }
                }

                while let Ok(menu_event) = menu_rx.try_recv() {
                    if menu_event.id == start.id() {
                        let _ = tx.send(AppCommand::RpcCommand(RpcCommand::Restart));
                    } else if menu_event.id == stop.id() {
                        let _ = tx.send(AppCommand::RpcCommand(RpcCommand::Stop));
                    } else if menu_event.id == quit.id() {
                        let _ = tx.send(AppCommand::Quit);
                        *control_flow = ControlFlow::Exit;
                    } else if menu_event.id == show.id() {
                        let _ = tx.send(AppCommand::UiCommand(UiCommand::ShowWindow));
                    }
                }
            }
            _ => {}
        }
    });
}

/// Creates the tray icon.
/// It loads it from `icon.bin` which is generated by `build.rs`.
fn create_icon() -> Result<Icon, TrayError> {
    let data = include_bytes!("../icon.bin");

    let w = u32::from_le_bytes(data[0..4].try_into().unwrap());
    let h = u32::from_le_bytes(data[4..8].try_into().unwrap());

    Icon::from_rgba(data[8..].to_vec(), w, h).map_err(|_| TrayError::IconDecode)
}
